//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParty()
        {
            this.tblPledgers = new HashSet<tblPledger>();
            this.tblStockMains = new HashSet<tblStockMain>();
        }
        [Key]
        public int intPartyId { get; set; }
        public Nullable<int> intCompanyId { get; set; }
        public string varPartyName { get; set; }
        public string varPartyType { get; set; }
        public string varAddress { get; set; }
        public string varContactNo { get; set; }
        public string varCity { get; set; }
        public string varCountry { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> intLevel1Id { get; set; }
        public Nullable<int> intLevel2Id { get; set; }
        public Nullable<int> intLevel3Id { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblLevel1 tblLevel1 { get; set; }
        public virtual tblLevel2 tblLevel2 { get; set; }
        public virtual tblLevel3 tblLevel3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPledger> tblPledgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockMain> tblStockMains { get; set; }
    }
}
