//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPermission
    {
        [Key]
        public int intPermissionId { get; set; }
        public Nullable<int> intRoleId { get; set; }
        public Nullable<int> intModuleId { get; set; }
        public Nullable<int> intComponentId { get; set; }
        public Nullable<int> intFieldId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
    
        public virtual tblComponent tblComponent { get; set; }
        public virtual tblField tblField { get; set; }
        public virtual tblModule tblModule { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
