//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStockDetail
    {
        [Key]
        public int intStockDetailId { get; set; }
        public Nullable<int> intStid { get; set; }
        public Nullable<int> intItemId { get; set; }
        public Nullable<int> intWarehouseId { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<decimal> dcRate { get; set; }
        public Nullable<decimal> dcAmount { get; set; }
        public Nullable<decimal> dcDisc { get; set; }
        public Nullable<decimal> dcDiscAmount { get; set; }
        public Nullable<decimal> dcExclTaxAmount { get; set; }
        public Nullable<decimal> dcTax { get; set; }
        public Nullable<decimal> dcTaxAmount { get; set; }
        public Nullable<decimal> dcInclTaxAmount { get; set; }
        public string varType { get; set; }
        public Nullable<decimal> dcPurRate { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblStockMain tblStockMain { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
