//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblRoles = new HashSet<tblRole>();
        }
        [Key]
        public int intUserId { get; set; }
        public Nullable<int> intCompanyId { get; set; }
        public string varName { get; set; }
        public string varEmail { get; set; }
        public string varAuthProvider { get; set; }
        public string varExternalId { get; set; }
        public string varPassword { get; set; }
        public string varAddress { get; set; }
        public string varCnic { get; set; }
        public string varContactNo { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public byte[] varPhoto { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRole> tblRoles { get; set; }
    }
}
